### ISSUE TITLE
mfgtools killed two SOM imx7-pico in just 1 month

### ISSUE THREAD

**Issue by neuberfran** [TechNexion/imx-mfgtools-tn#1]
Hi,

Please help-me with this:

https://community.nxp.com/message/1228990

**Comment by richard-hu** [comment]
@neuberfran :

Thanks for your feedback
.
I'm afraid that this place is intended to accept the issue feedback related to the software.
The mfgtool you use is not released by TechNexion officially.
The mfgtool you use is `mfgtool 2.0`, and it's not from this repository.
The mfgtool in this repository is `mfgtool 3.0 uuu`, it only supports i.mx8 so far.
Android things is the release made by third party - NXP and Google.

For this issue, I'd suggest to check if the problem is related to HW or SW.
[PreBuilt_OS_Image_Installation_Guide_v3.6.pdf](https://github.com/TechNexion/imx-mfgtools-tn/files/3828094/PreBuilt_OS_Image_Installation_Guide_v3.6.pdf)

Follow the guide to set the board to boot from `Serial download mode`.
Ensure the jumpers on the baseboard are contacted well on the baseboard.
Check if there is new device shown in "Device Manager" under Windows.
Or use "lsusb" command to check the device under linux.
If there is new device shown up, i'd suggest to change to use another host PC to test it again.
If the device is still not shown under your host PC.
It has much chance the HW gets damaged.
Then, there is nothing we can do by software to solve your problem.
Please contact  TechNexion customer support team (sales@technexion.com) to check the warranty.

BR,

**Comment by neuberfran** [comment]
1) @richard-hu Thank you so much for helping. I really need your help, as (as I will say below) you are the only Technexion that is willing to keep in touch with me. 

2) Unfortunately your tip didn't work. I have a HW problem.

3) How could a software (mfgtools) cause a Hardware Problem? What problem did it cause? How to find out?

4) **In this link:** https://drive.google.com/drive/folders/15fuQRezbaCGYj1AzPJTUs38xsHhrZJ28?usp=sharing  **have a pdf file name: AN5383**. In page 07 about **3.5. Hardware and software used** 

**I have question:**
4.a -> How can I make measurements without having OS installed on imx7? Would it work the same way as the PDF?

5) As shown in link below, because I communicated as an individual, I no longer have contact with Technexion. I really need to get this contact back. My two completed pico-imx7d starter kits were bought from two Google Developer Expert (GDE) gifts they received from Google (so I don't have an Invoice or invoice date)

5.a -> **Who is Marcel** ? Why doesn't he make things easier and sell me a new module? mouser e digi-key currently has no product in stock.

https://drive.google.com/drive/folders/13hH2imEwg9pTa8__HV7uuKTNFrOhQJHN?usp=sharing

**Comment by neuberfran** [comment]
@richard-hu
Why u don't talk more with me

**Comment by neuberfran02** [comment]
1.	@richard-hu Thank you so much for helping. I really need your help, as (as I will say below) you are the only Technexion that is willing to keep in touch with me.
2.	Unfortunately your tip didn't work. I have a HW problem.
3.	How could a software (mfgtools) cause a Hardware Problem? What problem did it cause? How to find out?
4.	In this link: https://drive.google.com/drive/folders/15fuQRezbaCGYj1AzPJTUs38xsHhrZJ28?usp=sharing hava a pdf file name: AN5383. In page 07 about 3.5. Hardware and software used
I have question:
4.a -> How can I make measurements without having OS installed on imx7? Would it work the same way as the PDF?
5.	As shown in link below, because I communicated as an individual, I no longer have contact with Technexion. I really need to get this contact back. My two completed pico-imx7d starter kits were bought from two Google Developer Expert (GDE) gifts they received from Google (so I don't have an Invoice or invoice date)
5.a -> Who is Marcel ? Why doesn't he make things easier and sell me a new module? mouser e digi-key currently has no product in stock.
https://drive.google.com/drive/folders/13hH2imEwg9pTa8__HV7uuKTNFrOhQJHN?usp=sharing

**Comment by neuberfran02** [comment]
I will call european police
